### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by orowith2os** [flathub/io.podman_desktop.PodmanDesktop#12]
Flathub automatically does a check on flatpak packages that have x-checker-data added, PodmanDesktop can use this too.

It might conflict with needing to generate sources however, so it might be best to make a custom workflow that updates the (external) sources and the manifest.

**Comment by benoitf** [comment]
hello @orowith2os , the flatpak package is updated when we cut a release in the main repository so I would say we don't need this external scanner.
