### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.podman_desktop.PodmanDesktop#23]
Since the Podman Desktop Flatpak seems to be an official one, it would be great if it could be verified.

Here are more details about verified apps: https://flathub.org/about

**Comment by benoitf** [comment]
thanks for the report

I've followed the doc, it is now `verified`

![image](https://github.com/flathub/io.podman_desktop.PodmanDesktop/assets/436777/3ab767a6-16b8-44c3-8b51-c0ce5954a7e8)
