### ISSUE TITLE
Question: podman does not exist /app/bin

### ISSUE THREAD

**Issue by jcleng** [flathub/io.podman_desktop.PodmanDesktop#29]
Question, how to use it in flatpak, my host is docker, no podman installed, after opening the software it says `podman` does not exist /app/bin, how do I configure the connection to docker?
`--filesystem=/run/docker.sock`  not working

**Comment by jeffmaury** [comment]
Do you have docker installed and running ? If yes it should be detected and you should see the images and containers

**Comment by jcleng** [comment]
> Do you have docker installed and running ? If yes it should be detected and you should see the images and containers您是否

yes , docker is running, and `/run/docker.sock` is run host computer

**Comment by jeffmaury** [comment]
Podman Desktop is using /var/run/docker.sock
