### ISSUE TITLE
Containers and images not found

### ISSUE THREAD

**Issue by spikhoff** [flathub/io.podman_desktop.PodmanDesktop#3]
Hi,

Something seems to be broken, I can't see my containers and images.
It says "No Container Engine / Configure/Start a container engine first".

```
$ podman images
REPOSITORY                                 TAG         IMAGE ID      CREATED      SIZE
registry.fedoraproject.org/fedora-toolbox  36          2110dbbc33d2  8 weeks ago  504 MB
```

```
$ podman ps
CONTAINER ID  IMAGE                                         COMMAND               CREATED     STATUS             PORTS       NAMES
843e715dd1bc  registry.fedoraproject.org/fedora-toolbox:36  toolbox --log-lev...  8 days ago  Up 24 minutes ago              fedora-toolbox-36
```

```
$ uname -a
5.19.11-200.fc36.x86_64
```

**Comment by benoitf** [comment]
hello @spikhoff it might be related to the socket not being available. It's normally started by podman Desktop.

What is your podman version ?

As workaround could you try something like
```
systemctl --user enable podman.socket
systemctl --user start podman.socket
```

**Comment by benoitf** [comment]
@spikhoff it's still not working ?

**Comment by benoitf** [comment]
ok understood. This is a bug, I'll investigate. Thanks for reporting

**Comment by eistak** [comment]
How do you command "systemctl --user enable podman.socket" on Mac OS?
I'm seeing the same issue spikhoff says above on my mac book.

**Comment by rienheuver** [comment]
Any progress on this? I know it was three years ago but I still run into exactly this issue..
